version: '3.8'

services:
    postgres:
        image: postgres:latest
        container_name: postgres-container
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis
        container_name: redis-container
        restart: unless-stopped
        ports:
            - '6379:6379'

    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: nodejs-app-container
        depends_on:
            - postgres
            - redis
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
        environment:
            - PORT=${PORT}
            - DB_HOST=postgres
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
            - GOOGLE_SMPT_HOST=${GOOGLE_SMPT_HOST}
            - GOOGLE_SMPT_PORT=${GOOGLE_SMPT_PORT}
            - GOOGLE_SMPT_USERNAME=${GOOGLE_SMPT_USERNAME}
            - GOOGLE_SMPT_PASSWORD=${GOOGLE_SMPT_PASSWORD}

volumes:
    postgres_data:
