version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-network

  redis:
    image: redis:7.0
    container_name: task_redis
    ports:
      - "6379:6379"
    networks:
      - task-network

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_node
    environment:
      - PORT=${PORT}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - GOOGLE_SMPT_HOST=${GOOGLE_SMPT_HOST}
      - GOOGLE_SMPT_PORT=${GOOGLE_SMPT_PORT}
      - GOOGLE_SMPT_USERNAME=${GOOGLE_SMPT_USERNAME}
      - GOOGLE_SMPT_PASSWORD=${GOOGLE_SMPT_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
      - redis
    networks:
      - task-network
    volumes:
      - .:/usr/src/app

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge
